### ISSUE TITLE
TypeError: window.__vue_hot__ is undefined

### ISSUE THREAD

**Issue by janat08** [Akryum/meteor-vue-component#34]
Copied getting started code from very bottom "all together now" and this pops up (error from title) in console. I'm using blaze+vue and am currently updating meteor from 1.3.2.

PS vue dependency goes into package.js rather than packages.js?

**Comment by janat08** [comment]
After update this pop-ups: Error: Cannot find module 'meteor-node-stubs/node_modules/http-browserify/lib/response'

Will see if just reinstalling packages will call on that as dependency.

**Comment by janat08** [comment]
`require()
 modules-runtime.js:112
require<.node_modules.meteor["akryum:vue-component-dev-client"].client["dev-client.js"]<()
 akryum_vue-component-dev-client.js:47
fileEvaluate()
 modules-runtime.js:180
require()
 modules-runtime.js:109
<anonymous>
 akryum_vue-component-dev-client.js:13145
<anonymous>
 akryum_vue-component-dev-client.js:11`

Reinstall hasn't helped. Will straight up copy the package.js from example app.

**Comment by Akryum** [comment]
> PS vue dependency goes into package.js rather than packages.js?
What do you mean by "vue dependency"? The vue library is autmatically added to your project `package.json` and installed.

> After update this pop-ups: Error: Cannot find module 'meteor-node-stubs/node_modules/http-browserify/lib/response'
Try `meteor npm install` to be sure all npm dependencies are installed.

**Comment by Akryum** [comment]
Have you tried with meteor 1.3.3?

**Comment by Akryum** [comment]
[Here](https://github.com/Akryum/meteor-vue-example) is a simple example project.

**Comment by janat08** [comment]
Error: Cannot find module 'meteor-node-stubs/node_modules/http-browserify/lib/response
require<.node_modules.meteor["akryum:vue-component-dev-client"].client["dev-client.js"]<()
 akryum_vue-component-dev-client.js:47

May be the issue that results in atom packages for Vue not working as "browserify" pop-ups when it comes to atom (syntax highlighting, ide, text editor, snippets).

**Comment by janat08** [comment]
"Meteor npm install" results in firefox:
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create
[HMR] Vue component hot reload shim applied.
Exception from Tracker afterFlush function:
Todos not defined

I'm guessing I wrote bad code, and this is working now.

**Comment by janat08** [comment]
Interestingly Atom syntax packages will now work instead of just being black and white although it's hardly any good (data, components, etc. won't highlight, and stuff that's highlighted is so interspersed and rare that plain .js may be better).

**Comment by Akryum** [comment]
> I'm guessing I wrote bad code, and this is working now, although prototype mutation may occur in my app rather than the package as I haven't written most of it.

So it's working now?

> Interestingly Atom syntax packages will now work instead of just being black and white although it's hardly any good (data, components, etc. won't highlight, and stuff that's highlighted is so interspersed and rare that plain .js may be better).

I use the following packages in atom:
- autoclose-html
- language-javascript-better
- language-vue
- meteor-api
- meteor-snippets
- pigments

Maybe we should add this to the guide?

**Comment by janat08** [comment]
I tried running example app for blaze, and it hasn't at all:
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EADDRINUSE
    at errnoException (net.js:905:11)
    at Server._listen2 (net.js:1043:14)
    at listen (net.js:1065:10)
    at Server.listen (net.js:1139:5)
    at meteorInstall.node_modules.meteor.vue-component.plugin.dev-server.js (packages/vue-component/plugin/dev-server.js:34:12)
    at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:153:1)
    at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:82:1)
    at node_modules/meteor/vue-component/node_modules/postcss-selector-parser/node_modules/uniq/uniq.js:57:1
    at node_modules/meteor/vue-component/node_modules/postcss-selector-parser/node_modules/uniq/uniq.js:57:1

a lot more gibberish.

**Comment by Akryum** [comment]
> Error: listen EADDRINUSE

The hot-reloading server port (currently 4242) is already in use. This is a [known issue](https://github.com/Akryum/meteor-vue-component/issues/31) (you can't launche two projects with the hot-reloading server). I'm currently working on a fix.

**Comment by janat08** [comment]
I'm not a fan of guides, it just gets past me. Firefox complains that object prototype is modified somewhere, ugh lol.

**Comment by Akryum** [comment]
> Firefox complains that object prototype is modified somewhere, ugh lol.

This is coming from the `meteor-node-stubs` npm packages, nothing to do witch vue or my packages.

**Comment by Akryum** [comment]
> Error: listen EADDRINUSE

Fixed in akryum:vue-component@0.3.6, see [updated doc](https://github.com/Akryum/meteor-vue-component/tree/master/packages/vue-component#hot-reloading)

**Comment by janat08** [comment]
Still having problems, must I use es6 import syntax even though I'm not using anything of the sort or define npm.depends somewhere? If I should use es6 import, how do I "enable" it for repository.

**Comment by Akryum** [comment]
You have to import the components or name them `.global.vue`, [see the doc](https://github.com/Akryum/meteor-vue-component/tree/master/packages/vue-component#manual-import)

**Comment by janat08** [comment]
Right, will try adding the actual error message here for ppl to find, but clearly not using es6 import syntax (how do I enable that for repo) I'd have to go and create global.vue then.

**Comment by Akryum** [comment]
If you are using meteor 1.3, you can use the import syntax. Just put your `.vue` files inside an `imports` directory in your project.

**Comment by janat08** [comment]
ugh lol. Never realized that whole enforcement of name-spacing and wtv else pretty much relied on you sticking into the folder.

**Comment by Akryum** [comment]
Do you still have the `TypeError: window.__vue_hot__ is undefined` error?

**Comment by janat08** [comment]
Nope
